### ISSUE TITLE
Salted Hash

### ISSUE THREAD

**Issue by JonasGeiping** [BrianPulfer/LMWatermark#1]
Hi, great implementation :)

A minor comment, I think you are using the default python `hash`. This hash function is salted by default, see https://docs.python.org/3/reference/datamodel.html#object.__hash__. A watermarked text fragment generated in this way, and saved to file, would later not be detectable in a new process, as the salt is unknown and python process-specific.

**Comment by BrianPulfer** [comment]
Hi @JonasGeiping !

Thank you very much for the heads-up! I didn't consider this issue at all. I will come up with a fix shortly.

By the way, congratulations on your work. It was a great and inspiring read! 😃

**Comment by BrianPulfer** [comment]
Solved in commit 2af0088.
